
services:
  app:
    container_name: Magix-Travel
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: magixtravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: magixtravel
      MYSQL_USER: magixtravel_user
      MYSQL_PASSWORD: Zsxolb@10
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
